### PR TITLE
Conversion to Swift 3

### PR DESCRIPTION
**Pull request by bwoods**

### CODE REVIEW

**Review by Antondomashnev — CHANGES_REQUESTED** [review]
Hey @bwoods thanks a lot for the PR, nice job 👍 . It has been a while I'm planning to migrate the project to Swift 3.

Could you please add a `swift-version` file and point it to 3.0 version and I would be happy to merge it 🎉

**Comment by bwoods** [comment]
Added `.swift-version` containing “3.0”

**Review by Antondomashnev — APPROVED** [review]

**Comment by Antondomashnev** [comment]
@bwoods thanks, I'll release a new podspec tonight 🚀

**Comment by Antondomashnev** [comment]
@bwoods the release version of 1.0.0 is ready.

**Pull request merged**
